services:
  redis:
    image: redis:alpine
    # Remove container_name
    networks:
      - app_net

  db:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=test_db
    ports:
      - "5432:5432"
    networks:
      - app_net

  energy-app:
    build: .
    volumes:
      - .:/django
    ports:
      - 8000:8000
    image: energy-app:django
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    networks:
      - app_net

  celery:
    restart: always
    build:
      context: .
    command: celery -A meter_readings worker -l INFO
    volumes:
      - .:/django
    depends_on:
      - redis
      - db
      - energy-app
    networks:
      - app_net

  celery-beat:
    restart: always
    build:
      context: .
    command: celery -A meter_readings beat -l INFO
    volumes:
      - .:/django
    depends_on:
      - redis
      - db
      - energy-app
    networks:
      - app_net

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    volumes:
      - ./data/pgadmin-data:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@root.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "5050:80"
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
