services:
  redis:
    image: redis:alpine
    container_name: redis

  db:
    container_name: postgresql_db
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=test_db
    ports:
      - "5432:5432"
    networks:
      app_net:
        ipv4_address: 192.168.0.2
  
  energy-app:
    build: .
    volumes:
      - .:/django
    ports:
      - 8000:8000
    image: energy-app:django
    container_name: energy_app_container
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    networks:
      app_net:
        ipv4_address: 192.168.0.4
  
  celery:
    restart: always
    build:
      context: .
    command: celery -A meter_readings worker -l INFO
    volumes:
      - .:/django
    container_name: celery
    depends_on:
      - redis
      - db
      - energy-app
  
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    volumes:
      - ./data/pgadmin-data:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@root.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "5050:80"
    networks:
      app_net:
        ipv4_address: 192.168.0.3

networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "192.168.0.0/24"
          gateway: 192.168.0.1