# Generated by Django 4.2.17 on 2024-12-19 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter',
            name='serial_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
